mipac4j:
  stateless: false
  login-url: /login.html
  logout-url: /logout.html
  index-url: /index.html
  three-landing-url: /three-landing.html
  callback-url: /callback.html
  exclude-path:
    - /login.html
    - /favicon.ico

logging:
  level:
    com.baomidou: debug