spring:
  thymeleaf:
    cache: false

mipac4j:
  stateless: false
  login-url: /login
  logout-url: /logout
  index-url: /index
  three-landing-url: /three-landing
  callback-url: /callback
  exclude-path:
    - /login
    - /auth/login
    - /favicon.ico
  cookie:
    http-only: true


logging:
  level:
    com.baomidou: debug