shaun:
  model: web_filter
  salt: ded4a7dc78674c6bb8ad15ffb1d4f974
  token-location: cookie
  enable-session: true
  expire-time: 10h
  login-url: /login
  logout-url: /logout
  sf-login-url: /sf
  callback-url: /callback
  exclude-path:
    - /auth/login
    - /favicon.ico
  cookie:
    domain: 127.0.0.1
#  matcher-names: csrfToken
#  authorizer-names: csrfCheck

spring:
  thymeleaf:
    cache: false
logging:
  level:
    com.baomidou.shaun: debug

