shaun:
  model: web_filter
  token-location: cookie
  enable-session: true
  expire-time: 10h
  login-url: /login
  logout-url: /logout
  sf-login-url: /sf
  callback-url: /callback
  exclude-path:
    - /auth/login
    - /favicon.ico
  matcher-names: csrfToken
  authorizer-names: csrfCheck

spring:
  thymeleaf:
    cache: false