spring:
  thymeleaf:
    cache: false

shaun:
  stateless: false
  login-url: /login
  logout-url: /logout
  index-url: /index
  three-landing-url: /three-landing
  callback-url: /callback
  exclude-path:
    - /login
    - /auth/login
    - /favicon.ico


logging:
  level:
    com.baomidou: debug