shaun:
  logout-url: /logout
  matcher-names: xssprotection,allowAjaxRequests
  exclude-path:
    - /login
    - /favicon.ico
  token-location: cookie

logging:
  level:
    com.baomidou.mipac4j.core.context.http: debug